version: '3'
services:
  mail:
    build: .
    volumes:
      - ./data:/data
      - ./vmail:/var/vmail
      #- ./mail/etc/dovecot/dovecot-sql.conf.ext:/etc/dovecot/dovecot-sql.conf.ext
      #- ./mail/etc/dovecot/conf.de/10-auth.conf:/etc/dovecot/conf.de/10-auth.conf
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: CHANGEME
      MYSQL_DATABASE: mail
      MYSQL_USER: mail
      MYSQL_PASSWORD: mailpassword
    volumes:
      - ./mysql:/var/lib/mysql
  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    ports:
      - 8000:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: mail
      POSTFIXADMIN_DB_NAME: mail
      POSTFIXADMIN_DB_PASSWORD: mailpassword
