version: '3'
services:
  mail:
    build: .
    volumes:
      - ./data:/data
      - ./mail/var/vmail:/var/vmail
      - ./mail/etc/dovecot/dovecot-sql.conf.ext:/etc/dovecot/dovecot-sql.conf.ext
      - ./mail/etc/dovecot/conf.de/10-auth.conf:/etc/dovecot/conf.de/10-auth.conf
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: notSecureChangeMe
      MYSQL_DATABASE: postfixadmin
      MYSQL_USER: postfixadmin
      MYSQL_PASSWORD: example
    volumes:
      - ./db/var/lib/mysql:/var/lib/mysql
  postfixadmin:
    depends_on:
      - db
    image: postfixadmin
    ports:
      - 8000:80
    restart: always
    environment:
      POSTFIXADMIN_DB_TYPE: mysqli
      POSTFIXADMIN_DB_HOST: db
      POSTFIXADMIN_DB_USER: postfixadmin
      POSTFIXADMIN_DB_NAME: postfixadmin
      POSTFIXADMIN_DB_PASSWORD: example